
package pe.gob.mtpe.sunateo.ws;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WsNotificacionesPortType", targetNamespace = "http://ws.sunateo.mtpe.gob.pe")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsNotificacionesPortType {


    /**
     * 
     * @param estado
     * @param idtransmision
     * @param errores
     */
    @WebMethod(action = "urn:confirmarRecepcionMensaje")
    @Oneway
    @RequestWrapper(localName = "confirmarRecepcionMensaje", targetNamespace = "http://ws.sunateo.mtpe.gob.pe", className = "pe.gob.mtpe.sunateo.ws.ConfirmarRecepcionMensaje")
    public void confirmarRecepcionMensaje(
        @WebParam(name = "idtransmision", targetNamespace = "http://ws.sunateo.mtpe.gob.pe")
        Long idtransmision,
        @WebParam(name = "estado", targetNamespace = "http://ws.sunateo.mtpe.gob.pe")
        Integer estado,
        @WebParam(name = "errores", targetNamespace = "http://ws.sunateo.mtpe.gob.pe")
        String errores);

    /**
     * 
     * @param idEntidad
     * @return
     *     returns byte[]
     */
    @WebMethod(action = "urn:obtenerNotificacionesPendientes")
    @WebResult(targetNamespace = "http://ws.sunateo.mtpe.gob.pe")
    @RequestWrapper(localName = "obtenerNotificacionesPendientes", targetNamespace = "http://ws.sunateo.mtpe.gob.pe", className = "pe.gob.mtpe.sunateo.ws.ObtenerNotificacionesPendientes")
    @ResponseWrapper(localName = "obtenerNotificacionesPendientesResponse", targetNamespace = "http://ws.sunateo.mtpe.gob.pe", className = "pe.gob.mtpe.sunateo.ws.ObtenerNotificacionesPendientesResponse")
    public byte[] obtenerNotificacionesPendientes(
        @WebParam(name = "idEntidad", targetNamespace = "http://ws.sunateo.mtpe.gob.pe")
        Integer idEntidad);

}
