
package pe.gob.mtpe.sunateo.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SunateoService", targetNamespace = "http://ws.sunateo.mtpe.gob.pe/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SunateoService {


    /**
     * 
     * @param arg0
     * @return
     *     returns pe.gob.mtpe.sunateo.ws.Transaccion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerNotificacionesPendientes", targetNamespace = "http://ws.sunateo.mtpe.gob.pe/", className = "pe.gob.mtpe.sunateo.ws.ObtenerNotificacionesPendientes")
    @ResponseWrapper(localName = "obtenerNotificacionesPendientesResponse", targetNamespace = "http://ws.sunateo.mtpe.gob.pe/", className = "pe.gob.mtpe.sunateo.ws.ObtenerNotificacionesPendientesResponse")
    public Transaccion obtenerNotificacionesPendientes(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "confirmarRecepcionMensaje", targetNamespace = "http://ws.sunateo.mtpe.gob.pe/", className = "pe.gob.mtpe.sunateo.ws.ConfirmarRecepcionMensaje")
    @ResponseWrapper(localName = "confirmarRecepcionMensajeResponse", targetNamespace = "http://ws.sunateo.mtpe.gob.pe/", className = "pe.gob.mtpe.sunateo.ws.ConfirmarRecepcionMensajeResponse")
    public String confirmarRecepcionMensaje(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
